# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Docker
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops

trigger:
  - main

resources:
  - repo: self



variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b5be6472-cd28-4b34-929d-1b4fc56d54e6'
  azureSubscription: 'Learning Lantern Group'
  dockerComposeFile: '**/docker-compose.yml'

stages:
  - stage: Docker
    jobs:
      - job: Docker
        displayName: Docker
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              dockerComposeFile: $(dockerComposeFile)
              action: 'Build services'
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              dockerComposeFile: $(dockerComposeFile)
              action: 'Push services'
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: 'learning-lantern'
              multicontainerConfigFile: $(dockerComposeFile)
