version: '3.4'

services:
  Seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "6001:80"

  ApiGateway:
    image: learninglantern.apigateway
    build:
      context: .
      dockerfile: ApiGateway/LearningLantern.ApiGateway/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - Seq
        
  Calendar:
    image: learninglantern.calendar
    build:
      context: .
      dockerfile: Calendar/LearningLantern.Calendar/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - Seq
      
  TodoList:
    image: learninglantern.todolist
    build:
      context: .
      dockerfile: TodoList/LearningLantern.TodoList/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - Seq