version: '3.4'

services:
  TodoList:
    image: learninglantern.azurecr.io/learninglantern.todolist
    build:
      context: .
      dockerfile: TodoList/LearningLantern.TodoList/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  Calendar:
    image: learninglantern.azurecr.io/learninglantern.calendar
    build:
      context: .
      dockerfile: Calendar/LearningLantern.Calendar/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  ApiGateway:
    image: learninglantern.azurecr.io/learninglantern.apigateway
    build:
      context: .
      dockerfile: ApiGateway/LearningLantern.ApiGateway/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - TodoList
      - Calendar