version: '3.4'

services:
  ApiGateway:
    image: ahmedezzatg/learninglantern.apigateway
    build:
      context: .
      dockerfile: ApiGateway/LearningLantern.ApiGateway/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80